spring.application.name=language_practical2

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Motomoto0410
spring.datasource.driver-class-name=org.postgresql.Driver